language: c

os:
  - linux
  - osx
  - windows

compiler:
  - gcc

script:
  - cd example
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then make && ./NComToCsv 171019_031603.ncom 171019_031603.csv; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then make && ./NComToCsv 171019_031603.ncom 171019_031603.csv; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then mingw32-make.exe && ./NComToCsv.exe 171019_031603.ncom 171019_031603.csv; fi
